### ISSUE TITLE
KeyError: 'Net Income_X'

### ISSUE THREAD

**Issue by seabass422** [Damonlee92/Build_Your_Own_AI_Investor#2]
At the end of Chapter 4.2, while running the app in Jupyter Notebook, I encounter a KeyError in the final cell output...

```
`KeyError                                  Traceback (most recent call last)
<ipython-input-39-96ae9c885c31> in <module>
      1 x_=pd.read_csv("Annual_Stock_Price_Fundamentals_Filtered_2020.csv", index_col=0)
----> 2 x_['Net Income'] = x_['Net Income_X'] # Net Income fix, checked annual reports.
      3 fixNansInX()
      4 addColsToX()
      5 x=getXRatios()

~\miniconda3\envs\machineLearning-env-py377\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3022             if self.columns.nlevels > 1:
   3023                 return self._getitem_multilevel(key)
-> 3024             indexer = self.columns.get_loc(key)
   3025             if is_integer(indexer):
   3026                 indexer = [indexer]

~\miniconda3\envs\machineLearning-env-py377\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 
   3084         if tolerance is not None:

KeyError: 'Net Income_X'`
```

**Comment by seabass422** [comment]
Alright, I think I fixed it by simply reversing things from:

`2    x_['Net Income'] = x_['Net Income_X']`

to:

`2    x_['Net Income_x'] = x_['Net Income']`

**Comment by Damonlee92** [comment]
Does it work fine if you ignore the line?

**Comment by seabass422** [comment]
I reversed the order of 'Net Income' and 'Net Income_' and it seems to have fixed the issue.

**Comment by seabass422** [comment]
Although now, while on the Altman Z Backtesting section (5th cell from the end/input line #68), I've run into this issue:

```
IndexingError                             Traceback (most recent call last)
<ipython-input-57-485c524e200c> in <module>
      4 # 7 greatest performance stocks of y_pred
      5 
----> 6 ticker_list = y[mask].reset_index(drop=True)[bl]["Ticker"].values
      7 stockRet = getStockTimeSeries(date_range, y_, ticker_list , mask, daily_stock_prices)

~\miniconda3\envs\machineLearning-env-py377\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3013         # Do we have a (boolean) 1d indexer?
   3014         if com.is_bool_indexer(key):
-> 3015             return self._getitem_bool_array(key)
   3016 
   3017         # We are left with two options: a single key, and a collection of keys,

~\miniconda3\envs\machineLearning-env-py377\lib\site-packages\pandas\core\frame.py in _getitem_bool_array(self, key)
   3066         # check_bool_indexer will throw exception if Series key cannot
   3067         # be reindexed to match DataFrame rows
-> 3068         key = check_bool_indexer(self.index, key)
   3069         indexer = key.nonzero()[0]
   3070         return self._take_with_is_copy(indexer, axis=0)

~\miniconda3\envs\machineLearning-env-py377\lib\site-packages\pandas\core\indexing.py in check_bool_indexer(index, key)
   2268         if mask.any():
   2269             raise IndexingError(
-> 2270                 "Unalignable boolean Series provided as "
   2271                 "indexer (index of the boolean Series and of "
   2272                 "the indexed object do not match)."

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
```

I've been tinkering around for a while but am missing something, clearly.  Have a sneaking suspicion it's a really obvious thing as well but this is my first complex project.

**Comment by seabass422** [comment]
If I skip that and the following three cells, I then run into this error when dealing with the S&P historical data:


```
NameError                                 Traceback (most recent call last)
<ipython-input-5-77e3adf40c36> in <module>
      1 # GSPC.csv taken directly from Yahoo.com is the S&P500.
----> 2 spy=pd.read_csv("GSPC.csv", index_col='Date', parse_dates=True)
      3 spy['Relative'] = spy["Open"]/spy["Open"][0]
      4 
      5 import matplotlib

NameError: name 'pd' is not defined
```

**Comment by seabass422** [comment]
No ideas?

**Comment by Damonlee92** [comment]
Email me at ai_investor@protonmail.com I'll try fix this stuff for you.

**Comment by Damonlee92** [comment]
That ways it's easier to check what you are executing at what time, the data in the files, etc.

Sorry it took me so long to get to you I didn't read anything after the original issue was resolved 20 days ago.

**Comment by MigDz** [comment]
Hello, I run into the same issue.  I tracked the dataframes and did,t see any "Net Income_x" column.  There is one "Net Income (Common)", though.  I have ignored that line and the program seems to run, but I am unsure of the accuracy of the results now.  Has this issue been solved?  Thanks

**Comment by Damonlee92** [comment]
Basically it depends if you use the paid version from SimFin or the free version. You can substitute similar column headings, e.g. "Net Income_x", "Net Income (Common)", and it will work similarly.

**Comment by MigDz** [comment]
Hello, Damon,

Many thanks. I will try that. Now I am with the free data, to learn and oractice, so that I can use it with the paid data when the earnings are published.

Atentamente,

J. Miguel Díaz
***@***.***

El dom, 22 dic, 2024 a las 04:34, Damonlee92 - notifications at github.com ***@***.***(mailto:El dom, 22 dic, 2024 a las 04:34, Damonlee92 - notifications at github.com <<a href=)> ha escrito:
